#!/usr/bin/env ruby

require "net/http"
require "pathname"

day = ARGV[0]&.to_i || Time.now.day
year = ARGV[1]&.to_i || Time.now.year

day_string = day.to_s.rjust(2, "0")
root = Pathname.new(__dir__)
dir = root.join(year.to_s).join(day_string)
code_path = dir.join("#{day_string}.rb")
input_path = dir.join("#{day_string}.txt")
cookie_path = root.join(".aoc-cookie")
day_url = "https://adventofcode.com/#{year}/day/#{day}"
input_url = "#{day_url}/input"

Dir.mkdir(dir) unless dir.exist?

unless input_path.exist?
  uri = URI(input_url)
  request = Net::HTTP::Get.new(uri)
  request["cookie"] = cookie_path.read.strip
  http = Net::HTTP.new(uri.host, uri.port)
  http.use_ssl = true
  File.write(input_path, http.request(request).read_body)
end

unless code_path.exist?
  File.write(code_path, <<~CODE)
    input = ""

    # input = File.read("#{input_path.basename}")

    input.lines.each do |line|
      p line
    end
  CODE
end

# system "code", dir.to_s
# system "open", day_url

puts "cd #{dir}"
